import type { Bookmark } from "@keeppage/domain";

export const mockBookmarks: Bookmark[] = [
  {
    id: "bm_guide_001",
    sourceUrl: "https://developer.chrome.com/docs/extensions/mv3/intro",
    canonicalUrl: "https://developer.chrome.com/docs/extensions/mv3/intro",
    title: "Chrome Extensions MV3 Overview",
    domain: "developer.chrome.com",
    note: "Capture profile switched to complete for code examples and iframe docs.",
    isFavorite: true,
    tags: [
      { id: "tag_browser", name: "browser" },
      { id: "tag_extension", name: "extension" },
    ],
    folder: {
      id: "folder_eng",
      name: "Engineering",
      path: "/engineering/extensions",
    },
    latestVersionId: "ver_guide_003",
    versionCount: 3,
    latestQuality: {
      score: 91,
      grade: "high",
      reasons: [],
      liveSignals: {
        textLength: 18742,
        imageCount: 17,
        iframeCount: 2,
        scrollHeight: 11840,
        previewable: true,
        screenshotGenerated: true,
        hasCanvas: false,
        hasVideo: false,
      },
      archiveSignals: {
        textLength: 18140,
        imageCount: 17,
        iframeCount: 2,
        scrollHeight: 11840,
        renderHeight: 11820,
        fileSize: 1498132,
        previewable: true,
        screenshotGenerated: true,
        hasCanvas: false,
        hasVideo: false,
      },
    },
    createdAt: "2026-03-17T10:35:00.000Z",
    updatedAt: "2026-03-17T10:36:12.000Z",
  },
  {
    id: "bm_article_002",
    sourceUrl: "https://webkit.org/blog/13895/auto-fill-updates/",
    title: "AutoFill Updates in Safari",
    domain: "webkit.org",
    note: "Possible iframe drop on embedded media section.",
    isFavorite: false,
    tags: [
      { id: "tag_web", name: "web-platform" },
      { id: "tag_research", name: "research" },
    ],
    folder: {
      id: "folder_reading",
      name: "Reading Queue",
      path: "/reading/browser-notes",
    },
    latestVersionId: "ver_article_002",
    versionCount: 1,
    latestQuality: {
      score: 76,
      grade: "medium",
      reasons: [
        {
          code: "iframe-loss",
          message: "Embedded media might be missing in archive result.",
          impact: 18,
        },
      ],
      liveSignals: {
        textLength: 7411,
        imageCount: 6,
        iframeCount: 1,
        scrollHeight: 6220,
        previewable: true,
        screenshotGenerated: true,
        hasCanvas: false,
        hasVideo: true,
      },
      archiveSignals: {
        textLength: 6802,
        imageCount: 5,
        iframeCount: 0,
        scrollHeight: 6144,
        renderHeight: 6130,
        fileSize: 528932,
        previewable: true,
        screenshotGenerated: true,
        hasCanvas: false,
        hasVideo: true,
      },
    },
    createdAt: "2026-03-16T09:11:00.000Z",
    updatedAt: "2026-03-16T09:14:00.000Z",
  },
  {
    id: "bm_thread_003",
    sourceUrl: "https://example.com/release-notes/alpha",
    title: "Alpha Release Notes (Internal Mirror)",
    domain: "example.com",
    note: "",
    isFavorite: false,
    tags: [{ id: "tag_release", name: "release-note" }],
    folder: {
      id: "folder_product",
      name: "Product",
      path: "/product/releases",
    },
    latestVersionId: "ver_thread_007",
    versionCount: 7,
    latestQuality: {
      score: 62,
      grade: "low",
      reasons: [
        {
          code: "text-loss",
          message: "Archive text is much shorter than source page.",
          impact: 25,
        },
        {
          code: "screenshot-missing",
          message: "Screenshot was not generated during capture.",
          impact: 5,
        },
      ],
      liveSignals: {
        textLength: 12400,
        imageCount: 11,
        iframeCount: 0,
        scrollHeight: 9020,
        previewable: true,
        screenshotGenerated: true,
        hasCanvas: true,
        hasVideo: false,
      },
      archiveSignals: {
        textLength: 7421,
        imageCount: 8,
        iframeCount: 0,
        scrollHeight: 8550,
        renderHeight: 8480,
        fileSize: 301210,
        previewable: true,
        screenshotGenerated: false,
        hasCanvas: true,
        hasVideo: false,
      },
    },
    createdAt: "2026-03-15T14:20:00.000Z",
    updatedAt: "2026-03-18T02:20:00.000Z",
  },
];
